### ISSUE TITLE
error: 'TWBR' was not declared in this scope

### ISSUE THREAD

**Issue by Genoil** [SpenceKonde/ATTinyCore#106]
I'm trying to use a library that depends on the Wire library, but I can't get around the following error:

/Users/*****/Library/Arduino15/packages/ATTinyCore/hardware/avr/1.1.2/libraries/Wire/Wire.cpp:82:3: error: 'TWBR' was not declared in this scope

How can I fix this?

(using tiny84 with arduino 1.8.1 on OSX)

**Comment by SpenceKonde** [comment]
You need to use an I2C library that is compatible with the tiny84 - The stock Wire library depends on the chip having hardware I2C support, while the Tiny84 only has a USI. The USI can be used to do I2C, but it needs a different library - https://github.com/SpenceKonde/TinyWireM (assuming you're using it as an I2C master)

Unfortunately, you'll also need to modify the library you're using to include TinyWireM  instead of Wire, and possibly make other changes to the library to account for differences between TinyWireM and Wire. 

My plan is to create versions of SPI and Wire libraries to include with the core that will detect the appropriate implementation of I2C (or SPI) for the chip hardware, and present a unified API that will "just work" with existing libraries. The issue for that is here - https://github.com/SpenceKonde/ATTinyCore/issues/53 - I just haven't had time to implement it yet, as it's a rather big deal. I am acutely aware of how important this feature is to people.

**Comment by Genoil** [comment]
Thanks. Our prototype was using a Trinket (tiny85) which was working with their port of Wire, but I couldn't figure out to make it work with my tiny84. Ultimately fixed it with with some global find and replace Wire > TinyWireM in the I2C device libraries. Sorry to bother you.

**Comment by SpenceKonde** [comment]
Glad to hear you got it sorted!

As I said, I realize this process kinda sucks. I'm working on the better solution for the future.

**Comment by manix** [comment]
I am getting this error when I try to compile my code for an attiny24. When I go to the lib suggested in comment 2 I see that I should not install it and that Wire.h should be supported, I'm using ATTinyCore 2.0

How can I resolve this issue?

Thanks!

---

After some debugging, I noticed that it is trying to compile the default Wire library and not the one from ATTinyCore. I'm not very experienced with the arduino makefile builds so I'm not entirely sure how I'm supposed to tell it to use the latter, so I just made a symlink:

    sudo ln -s /usr/share/arduino/hardware/ATTinyCore/avr/libraries/Wire/src /usr/share/arduino/libraries/TINYWire

Then added it in the makefile:

    ARDUINO_LIBS = TINYWire

And now it's trying to compile the correct library but I'm getting this:

```
/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=attiny24 -Wl,--gc-sections -Os -flto -fuse-linker-plugin -o build-attinyx4-24/bms.elf build-attinyx4-24/main.ino.o build-attinyx4-24/libcore.a   -lc -lm 
build-attinyx4-24/libcore.a(Wire.cpp.o): In function `TwoWire::begin(unsigned char)':
Wire.cpp:(.text._ZN7TwoWire5beginEh+0xe): undefined reference to `USI_TWI_Slave_Initialise'
build-attinyx4-24/libcore.a(Wire.cpp.o): In function `TwoWire::write(unsigned char)':
Wire.cpp:(.text._ZN7TwoWire5writeEh+0x3c): undefined reference to `USI_TWI_Space_In_Transmission_Buffer'
Wire.cpp:(.text._ZN7TwoWire5writeEh+0x44): undefined reference to `USI_TWI_Transmit_Byte'
build-attinyx4-24/libcore.a(Wire.cpp.o): In function `TwoWire::available()':
Wire.cpp:(.text._ZN7TwoWire9availableEv+0x14): undefined reference to `USI_TWI_Data_In_Receive_Buffer'
build-attinyx4-24/libcore.a(Wire.cpp.o): In function `TwoWire::read()':
Wire.cpp:(.text._ZN7TwoWire4readEv+0x2a): undefined reference to `USI_TWI_Receive_Byte'
build-attinyx4-24/libcore.a(Wire.cpp.o):(.data._ZN7TwoWire6BufferE+0x0): undefined reference to `TWI_Buffer'
collect2: error: ld returned 1 exit status
make: *** [/usr/share/arduino/Arduino.mk:1442: build-attinyx4-24/bms.elf] Error 1
```
