### ISSUE TITLE
Attiny44 - Wrong default pin mapping for boad-manager

### ISSUE THREAD

**Issue by cimba007** [SpenceKonde/ATTinyCore#147]
Hi, 

I added your wonderful core to the boardmanager and it took me a whole day to find out there are TWO different pin mappings (drop one please!!!!)

Now to my point .. the "alternative" pin Mapping is wrong.

https://github.com/SpenceKonde/ATTinyCore/blob/master/avr/extras/ATtiny_x4.md

This is the default option 

![image](https://user-images.githubusercontent.com/3453121/27984483-4b6b0908-63d7-11e7-84f9-a607a848b3ae.png)

As you can see default is AttinyCore .. so far so good .. but the picture says AttinyCore is the "alternative pinout" .. it would be nice to clarify the picture.

**Comment by SpenceKonde** [comment]
I belive the issue with the default core is fixed in the github version, which I'm hoping to get into the board manager release within the coming days (there is one last critical issue that I need to test my fix for prior to release). 

Unfortunately, I can't drop either pinout without breaking existing code - both pin mappings were widely used, so I can't drop either of them without breaking backwards compatibility, which is always my primary concern.
