### ISSUE TITLE
ATTINY13 support?

### ISSUE THREAD

**Issue by colesnicov** [SpenceKonde/ATTinyCore#163]
Hi anyone. It support ATTINY13 chips? I reffer to https://github.com/SpenceKonde/ATTinyCore/issues/89#issuecomment-255555901, https://github.com/sleemanj/ATTinyCore and  https://github.com/sleemanj/optiboot/tree/master/dists#attiny ... Yep, and https://github.com/damellis/attiny , https://github.com/bartgee/at13. Why do you didnt implement this too?

**Comment by SpenceKonde** [comment]
No, use MCUdude's MicroCore for the tiny13.

**Comment by sleemanj** [comment]
My fork implemented a lot of optimisation work so that the Tiny13,
4,5,9,10 (and x5, x4) will be useful with ATTinyCore, including print,
serial and tone. 

My distribution of my core (the optiboot repository link you posted)
also departs in heavier use of the boards sub-menu system for those
supported chips to enable the user to pick-and-choose various
optimisation types.  My distro also uses my fork of optiboot (hence
where it lives) instead of the ATTinyCore bootloader binaries but that
is a minor difference really in practical terms, of course the
13/4/5/9/10 don't have bootloaders anyway, no room to waste. 

Spence is always welcome to merge any or all of my fork back, but I can
appreciate how that might be a dawnting task to pick through especially
if he's not familiar with those chips. 

I'm not very familiar with the alternative MCUdude core spence refers
too so I can't say why he might feel that is a better choice. 

On 2017-09-04 03:05, Colesnicov Denis Petrovich wrote:

> Hi anyone. It support ATTINY13 chips? 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1] https://github.com/SpenceKonde/ATTinyCore/issues/163
[2]
