### ISSUE TITLE
Full-Speed SPI Master attiny1634

### ISSUE THREAD

**Issue by alessio31183** [SpenceKonde/ATTinyCore#164]
Hi,
I'm using the SPI library under your attiny package on the ATtiny1634.
Something strange happens when I try to change the SPI clock frequency.

Using the SPI.beginTransaction(SPISettings(clockDiv, MSBFIRST, mode)) changing the clockDiv I get the same result each time.
The clock is fixed to 500KHz.
I'm working with the 8MHz internal oscillator
Theorically the max speed should be fsck = fck /2 as per datasheet @ pag138

In the SPI.cpp source file there is this function:
void tinySPI::setClockDivider(uint8_t clockDiv)
{
  // CD - this routine currently does nothing as clock dividers for the
  //      software driven USI SPI bus are ignored for this first cut
  uint8_t dummy; // Nothing routine (needed so not optimised away)
}

Then I supposed that the clock setting has not been implemented yet.

What I have to do if I want to change the clock speed.
Is this feasible in my sketch manually? 

So the issue is how to change the speed of USICLK or USITC strobe bits?

**Comment by SpenceKonde** [comment]
The test in the while loop on line 308 is what's slowing it down I think - since it gets evaluated twice per bit, even a very simple test requires enough calculation to dramatically slow it down. I'm not sure what the right approach toward solving this is; in any event, fixing this falls under https://github.com/SpenceKonde/ATTinyCore/issues/134
