### ISSUE TITLE
Change SoftwareSerial Pins(Attiny85)

### ISSUE THREAD

**Issue by nathanRamaNoodles** [SpenceKonde/ATTinyCore#194]
Is there a way to change the hardware serial pins for the Attiny85.  I need the only two digitalPins which are Ain0 and Ain1.  Perhaps we could move them to ADC3 and ADC2.  I learned that software serial is available on analog pins after all.

**Comment by SpenceKonde** [comment]
There is no hardware serial on the Tiny85 - it's a software implementation based on the analog comparator interrupt (so it's more compatible with other libraries than most implementations which use PCINTs, and would conflict with any other library that needed PCINT on tiny85, since the tiny85 has only one port). It is named "Serial" to make it easier to move code to tiny85 from parts with a hardware serial port. That said, no, it cannot be moved - the TX pin could (in theory) be changed, but not RX, because the analog comparator input is only available on one pin. 

I am confused by your statement that there are only two digital pins. All of the pins (except reset) can be used as fully functional digital pins, same as any other Arduino (this seems to be a common point of confusion, due to the way Arduino's documentation presents things - "analog pins" are fully functional digital pins that can also do analog voltage readings. There are only two analog-only pins in the entire 8-bit avr product line: A6 and A7 on the smd version of 328p (and it's smaller-flash versions)). 

If you need a serial port, and AIN0/AIN1 are in use, use SoftwareSerial, AltSoftwareSerial, or other similar library - there are many, most of which should work on the tiny85 without issue (though they all have different caveats, so read their docs carefully. Software serial implementations are all troublesome in different ways, which is largely what led to me starting work on this core - I wanted the tiny841 with its dual hardware serial ports working with arduino)
