### ISSUE TITLE
Question about 1.1.5

### ISSUE THREAD

**Issue by beicnet** [SpenceKonde/ATTinyCore#199]
Hi there,

Can't install it manually, tried all things, but seems not working!

Can you release the Boards Manager version?

Regards

**Comment by SpenceKonde** [comment]
Board manager version is released now; it can take up to a day between the "release" being created and the board manager version being available through board manager due to steps involved in making the board manager json - that is done by @per1234 - and it needs to then be uploaded, which I couldn't do during the day because I didn't have the key file for SCP login on me. 

Manual install instructions are here, for reference: https://github.com/SpenceKonde/ATTinyCore/blob/master/Installation.md

**Comment by beicnet** [comment]
@SpenceKonde Thank you, yes, I tried the manual installation, both method and did NOT work... :disappointed:
