### ISSUE TITLE
External Interrupts on ATTiny841

### ISSUE THREAD

**Issue by kasparsd** [SpenceKonde/ATTinyCore#224]
We currently report only pin 1 as a valid interrupt pin:

https://github.com/SpenceKonde/ATTinyCore/blob/e5824581b2adef573e9bffc0af8ebd9b07aa9f57/avr/cores/tinymodern/core_pins.h#L63

However, the datasheet has the following:

> External Interrupts are triggered by the INT0 pin, or by any of the PCINTn pins. Note that, if enabled, the interrupts will trigger even if the INTn or PCINTn pins are configured as outputs. This feature provides a way of generating software interrupts.
> 
> The pin change interrupts trigger as follows:
> - Pin Change Interrupt 0 (PCI0): triggers if any enabled PCINT[7:0] pin toggles
> - Pin Change Interrupt 1 (PCI1): triggers if any enabled PCINT[11:8] pin toggles

Should this be updated to return `0` for pins `PCINT[7:0]` and `1` for pins `PCINT[11:8]`, and the relevant parts in [WInterrupts.c](https://github.com/SpenceKonde/ATTinyCore/blob/1ea94680ba82fb87b33d327357ed54902674cc48/avr/cores/tinymodern/WInterrupts.c)?

**Comment by SpenceKonde** [comment]
This is correct behavior. 

In order to maintain predictable behavior, we follow the same behavior as the official core uses for Arduino API functions, including the digitalPinToInterrupt() macro - it only reports full-featured "external interrupt" pins, those numbered INTn where n is a number in Atmel's pin function scheme; these are the pins supported by attachInterrupt() (and this is what this macro is normally used with). Pin Change interrupts are not included. 

Pin change interrupts have more limited functionality, and cannot be used with attachInterrupt(), can only trigger on change (not edge or level), and are triggered in two banks, requiring the ISR to be smart enough to read the pins and figure out what change occurred - though at the same time, with direct port reads, this can be an asset, for example when reading rotary encoders (particularly multiple rotary encoders on the same port).

**Comment by kasparsd** [comment]
Thanks for the detailed explanation @SpenceKonde! Understood!
