### ISSUE TITLE
What's the different between with optiboot or not?

### ISSUE THREAD

**Issue by segatecm** [SpenceKonde/ATTinyCore#315]
HI, 
I'm new one to the ATTiny. I want to use tiny44. 
But I dont know how to choose the board, the option with optiboot or not? What 's the different between those?

Thank's for help!

**Comment by SpenceKonde** [comment]
If you wish to program it via an ISP programmer (using the SPI pins and Reset), use no bootloader. This gives you more space for your sketch and also allows slightly faster upload; we recommend this option for all parts except those that have a hardware serial port and 8k or more of flash (ie, the 841, 1634, 87,167, and 828 - it was added for other parts due to strong and persistent demand, even though I do not think it provides a good developer experience)

If you wish to program it through a bootloader, using a serial adapter (using software serial, since the tiny44/84 does not have hardware serial. See the part-specific documentation page for the pins), select the Optiboot option. This reduces the space available for the sketch, since some space is taken by the bootloader (again, see the part specific documentation pages - there's a page for every supported part that describes the options and available flash space), though it may be more (or less) convenient depending on your application. 

Either way, after selecting the desired clock source, EESave and BOD settings, you must use an ISP programmer to do "burn bootloader" to set the fuses for those options, and to upload the bootloader (if any) prior to uploading any sketch.
