### ISSUE TITLE
Two copies of 48/88 pinout

### ISSUE THREAD

**Issue by prandeamus** [SpenceKonde/ATTinyCore#432]
You see to have two copies of the Attiny48/88 pinout in README.md

On the home page: https://github.com/SpenceKonde/ATTinyCore they are being referenced by two different URLs

https://camo.githubusercontent.com/8cf54c35bf59982d0b678ace2a9a6053ca2d6fc7/687474703a2f2f6472617a7a792e636f6d2f652f696d672f50696e6f75745438382e6a7067

and also

https://raw.githubusercontent.com/SpenceKonde/ATTinyCore/master/avr/extras/Pinout_x8.jpg

(A small matter, but I want you to know people do read this stuff!)

**Comment by SpenceKonde** [comment]
Thanks for reporting, trivial fix - for some reason one was pointing to the image on my website instead of the one in the repo (hence the dumbass URL - github caches images so people can't use them to track visitors if they host the image themselves). One of them was supposed to be the one for the DIP pinout. Now it is.

Not sure how long it has been broken. I have a bad feeling that the answer is "a very long time" - I have
