### ISSUE TITLE
Uploading from Arduino IDE

### ISSUE THREAD

**Issue by ArduinoShop** [SpenceKonde/ATTinyCore#468]
I am looking to use your package with an ATtiny85 development board with USB - similar to offerings from DigiSpark.

I am using a fresh install of the 1.8.13 IDE and ver. 1.4.1 of you package...

everything works fantastic until I flash your micronucleus bootloader onto a virgin chip and then
put the chip into the dev board.. When I try to upload from the IDE via /dev/ttyUSB0 it asks me to plug in the board...
and when I do it just repeats a message like:

--  Device reports version as: 2.5
--  Warning: device with unknown new version of Micronucleus detected.
--  This tool doesn't know how to upload to this new device. Updates may be available.

If I use a chip with a micronucleus bootloader from the micronucleus github I get the same result except it complains about version 2.4

not sure what to do...

When I

**Comment by SpenceKonde** [comment]
Please see https://github.com/SpenceKonde/ATTinyCore/issues/465

We are in the middle of a long discussion about this - in short, nobody has made a set of prebuilt binary packages available since dinosaurs walked the earth; everyone seems to have been "not my problem"-ing it and building their own binaries if they needed them - ATTinyCore support has sort of shown a spotlight on this and we're working on a way forward.
