### ISSUE TITLE
Share same pins between SPI and I2C

### ISSUE THREAD

**Issue by garudaonekh** [SpenceKonde/ATTinyCore#542]
Hello,
I use attiny85. I can get my NRF24L01 to works and I2C LCD to works separately but when I merge them using this wiring below, it get hangs. Any suggestion or better solution?

https://github.com/chaeplin/esp8266_and_arduino/tree/master/_51-attiny85-nrf24-lcd-getntp

**Comment by prandeamus** [comment]
Pull up resistors missing?

**Comment by SpenceKonde** [comment]
I am shocked that anyone made that work....  I2C does not permit arbitrary non-I2C signals on SCL/SDA.

**Comment by garudaonekh** [comment]
> Pull up resistors missing?

I am not sure too but based on that link's diagram no resistors needed.

**Comment by SpenceKonde** [comment]
**Pull up resistors are always required for I2C**. Sometimes they are included on the breakout board for I2C devices, sometimes not, sometimes they are included but you have to complete a solder bridge to enable them, etc.  **Pull up resistors are always required for I2C**
With a one or a small number of I2C devices on short wires on boards that can enable internal pullups (the tinyAVRs cannot because of how the USI works), it may work without it, but it is way outside of the I2C spec -pullup resistance is supposed to be what, 4.7k tops?

My cores do not turn on pullups - no resistors generally results in no response. That is much easier to debug than if it worked depending on what devices you had on i2c bus, and how long the wires are. 
 **Pull up resistors are always required for I2C** 

If you ever find yourself with an I2C thing that isn't working, the first thing I'd do is check resistance to the positive supply rail (assuming that's what voltage I2C is using for signaling). from SCL and SDA.

**Comment by garudaonekh** [comment]
> I am shocked that anyone made that work.... I2C does not permit arbitrary non-I2C signals on SCL/SDA.

It look like the source code is from China. Anyhow, suggestion is much appreciated as I am new to all this.

**Comment by SpenceKonde** [comment]
That all aside, the fact that you say it worked with just the LCD on the same pins would indicate that somehow, there are pullups there...

**Comment by garudaonekh** [comment]
> That all aside, the fact that you say it worked with just the LCD on the same pins would indicate that somehow, there are pullups there...

LCD+SHT30 I2c(Humidity sensors) alone works. NRF24L alone also work. but when I put togethers, it's not.

**Comment by SpenceKonde** [comment]
Closed because without more evidence that it is viable, I have no reason to expect that the configuration shown would work, and hence no reason to think it is a defect in the core. 

multiple I2C devices on one bus is supported, I 2C prtotocol has mechanisms for devices to know when they;'re being talked to.
