### ISSUE TITLE
Attiny861 PWM on PB5  makes PB4 not usable

### ISSUE THREAD

**Issue by Baffless** [SpenceKonde/ATTinyCore#614]
The problem that if i use PWM on attiny861 PB5 pin i can't use PB4 as simple digital out. As if i set pinmode to output on PB4 it automatically  outputs inverted PB5 PWM signal.Same with other PWM pin pairs.in example this code 
`//attiny861 with spencekonde attinyCore
void setup() 
 {
  pinMode (12, OUTPUT);
  pinMode (13, OUTPUT);  
  analogWrite(13, 10);
  }  

void loop() {
  
  }`

So the question is this a bug or my misunderstanding?  According to datasheet this depends on PWM mode selected. And i suspect it could be changed manually with TCCR1X registers or so. I could not succeed.Just partially.  Maybe my understanding is bad. Or maybe it is impossible on this chip? Datasheet is hard to grasp.   Where is the problem and what should be a solution?  Interested what PWM mode is used with analogWrite?

Regards,
Rytis

**Comment by SpenceKonde** [comment]
I don't know off hand and that sounds... so mewhat familiar. 

What *ARE(* we setting ., I knoe in the past that I ma have been a touh aggressive with trying to get more channels out and lax in testing... My read of the datasheet makes it look entirely possible to use just one of the channels, and in fact says that both will only be coonenected in one mode. Can you check what the values of the regiters I mean, Ideally all the TCCR1 rbut especiially TCCR1D, and the value of the WGM bits. Considering that nothing based on any verison of the core prior to 2.,0.0 is not going to be actionable, since these things ahave already gotten heavily remodeled, I don't think I will take time away from getting 2.0.0 out. DxCore 1.3.7 is coming out this week. 

After I shove DxCore 1.3.7 out I will need someplace to come hide while the angry users try to hunt me down over all the shit I've most certainly broken over there... Like, all the hard parts of 2.0 .0 are done. the things  I have n't done yet is buildl boards,txt (from scratch, 100% redone, because it was too much of a shitshot

meant to do a small release ust to clean up some documentation , fix a couple of criticals, and then come over here, but next thin I know,  it's 3 weeks later, and I'm reimplementin because like, it has to take over all the vectors it works with. HEre there are INTn interrupts, and PCINTS, Modern AVRs have only somrthing that works like a PCINTm, only you get to configure INTn-style options on a per pin basis, So essentially evey pin is an INTn pin.... and hence EVERY PIN VECTOR IS TAKEN OVER AN D YOU CAN'T DEFINE ANY MANUALLY, like if attaching something to INT1 also made it so trying to define interrupts and attachInterrupt is inherently slow  because it's calling a function it can't inline and optimize for. But anway, enough about that. 

ATTiny Core innearly ready for it's final major release. , all I need to fo is figure out how I'm going to getnerate the boards file. Platform.txt is ready, now, the whole thing pulls in a bunch of spiffy stuff from the modern avr dcores in terms of features from that ande It is a ***HUGE*** set of chages Every variant file was completely redone,

**Comment by Baffless** [comment]
Ok thanks for such long answer.More or less i understood.  I didn't know Dxcore 1.3.7 which is very interesting indeed. Anyway i have my workaround with TCCR1D and some other registers just PWM inverted and 0 and 255 values  can't be used. And also have some hardware workarounds , so the board will work anyway. It is just not the way i intended.  
Good luck with the new project!

**Comment by SpenceKonde** [comment]
I don't even know where my 861 hardware got off to (I have some somewhere, I'm sure, I know I'm sold out of them on Tindie, but I never sell the first one I make, I have to test it. , but I think this could be a simple fix.
the only time inverted PWM should be coming out as far as I can see in the datasheet is if bits 3:2 of TCCR1C were 01. ie if  ((TCCR1C & 0x0C) >>2) == 1. That would indicate that the core is setting it wrong.... 
Try 

```
#define LED_PIN2 (some pin with an LED and resistor on it)
#define LED_PIN3 (some pin with an LED and resistor on it)
void setup()
{
pinMode(LED_PIN2,OUTPUT)
pinMode(LED_PIN3,OUTPUT);
pinMode (12, OUTPUT);
pinMode (13, OUTPUT);
analogWrite(13, 10);
_NOPNOP(); // rjmp .+0 - 1 word 2 cycle nop
_NOPNOP(); // and 2 more.
 /*They don't really describe how synchronization is done on high speed async timer
  * but I've been screwed by that before on x61, and it's the predecessor to TCD0 on tinyAVR 
  * 1-series and Dx-series)  whereas there it is impossible to ignore and they are very explicit in the 
  * datasheet in the 861 datasheet, you could completely miss it until it breaks in a wacky way. 
  * 4 clocks is more than enough if there needs to be a sync delay so we should be good now */
   // Now check the bits since you probably don't have a way to get serial data out: 
digitalWrite(LED_PIN2,TCCR1C & (1 << 2)); // This should be off/low (I suspect you will find it is high)
digitalWrite(LED_PIN3,TCCR1C & (1 << 4)); // This should on/high (I suspect you will find the opposite)
}
void loop() {}`
```

Assuming that confirms my hypothesis, then this should work around it until the next release:
```
void setup()
{
pinMode (12, OUTPUT);
pinMode (13, OUTPUT);
analogWrite(13, 10);
_NOPNOP(); // rjmp .+0 - 1 word 2 cycle nop
_NOPNOP(); // and 2 more.
 /*They don't really describe how synchronization is done on high speed async timer
  * but I've been screwed by that before on x61, and it's the predecessor to TCD0 on tinyAVR 
  * 1-series and Dx-series)  whereas there it is impossible to ignore and they are very explicit in the 
  * datasheet in the 861 datasheet, you could completely miss it until it breaks in a wacky way. 
  * 4 clocks is more than enough if there needs to be a sync delay so we should be good now */
   // Now check the bits since you probably don't have a way to get serial data out: 
   TCCR1C = (TCCR1C & (~0x0C)) | 0x08;
}
void loop() {}
```
If that works, remove the NOPNOPs and see if it still works.

Either way please let me know so I can fix the core if it is actually writing that register incorrectly or clearly document the issue if that *doesn't* work.

**Comment by Baffless** [comment]
This fix works! Respect and thanks! This line TCCR1C = (TCCR1C & (~0x0C)) | 0x08; should go after every time i analogwrite to pin13 and analogwrite with value 255 can't be used,but it works.

p.s. not related but  1Mhz clock source (internal) works ok, but 8Mhz clock source(internal) takes 8 times longer to execute delay() command.

**Comment by SpenceKonde** [comment]
> p.s. not related but 1Mhz clock source (internal) works ok, but 8Mhz clock source(internal) takes 8 times longer to execute delay() command

Per the readme:
"When using a chip for the first time, or after changing the **clock speed**, EESAVE or BOD settings, you must do "burn bootloader" to set the fuses"

**Comment by SpenceKonde** [comment]
BTW it's probably broken on the other PWM pins if the pin next to them is set OUTPUT, too.

**Comment by Baffless** [comment]
> BTW it's probably broken on the other PWM pins if the pin next to them is set OUTPUT, too.

I think yes. Just not 100% sure. As my circuit doesn’t use these pins that way i can’t remember if i tested this. But i think i have tested and it didn’t work just cant remember.
