### ISSUE TITLE
Pinout chart unclear regarding MISO and MOSI pins

### ISSUE THREAD

**Issue by pprakash** [SpenceKonde/ATTinyCore#644]
Hi,

Thanks for the wonderful Core. 

Am working on RF24 communication between ATTiny84 and UNO. During the process I noticed that the MOSI and MISO pins are swapped in the pins_arduino.h file. 
`#define MOSI 5 
#define MISO 6 `

As per pin out [https://github.com/SpenceKonde/ATTinyCore/blob/master/avr/extras/ATtiny_x4.png](url) MOSI should be at 6 and MISO should be at 5. 

I tried swapping this in the **tinyX4_reverse/pins_arduino.h** file but its not taking effect. 

Please let me know the procedure for swapping the same.

ATTinyCore Version 1.5.2.
Arduino Version 1.8.16

**Comment by SpenceKonde** [comment]
Both the pinout chart and pins_arduino are correct. 

The pins marked MISO, MOSI, and SCK on te pinout chart are for the ISP programming interface when used to program the chip. 

That is the only functionality that has a MISO or MOSI pin. 

When using the USI for SPI-like communication, there is no "MISO" or "MOSI" , pins that change whether they are inputs or outputs based on whether the device is master or slave. The USI has only DI and DO (Data In and Data Out). If the device is an SPI master, DI is MISO, when it is a slave, DO is MISO. 

The ISP and the USI use the same pins. When the device is programmed via ISP, it acts like an SPI slave with the reset pin serving the role of an active low chip select. Hence MISO DO, and MOSI is DI. 

The supplied universal SPI library is a special version which automatically uses the correct implementation (either hardware SPI, or the USI) depending on the chip at hand. Since the SPI library (like every library called SPI.h ever) only supports operation as a master mode, and since a large amount of code in the wild is written with the assumption that MISO, MOSI, and SCK are defined to point to those pins, compatibility requires that those pins be defined appropriately for master operation, that is, MISO is DI, and MOSI is DO. The pins_arduino is thus correct. I state in the documentation that on parts that use USI, MISO is DI and MOSI is DO, and have a separate color for the MISO and MOSI pins on the pinout chart in an attempt to make clear that those pin names are not applicable to the USI as SPI. It is apparent that this is NOT  made clear

Please let me know how I could change the documentation to make this point clear; I have been extremely frustrated by the fact that nothing I have done in the documentation has prevented people from expecting that the pin connected to MOSI for ISP programming is not the pin that acts as MOSI when the device is using the USI to act as an SPI master.

**Comment by SpenceKonde** [comment]
I have renamed this topic to accurately reflect the nature of this issue. This is a documentation problem, bug in the behavior of the core. 

I have no idea what you hoped to achieve by changing pins_arduino.h - it can't change which pin has what function. The pins that have those functions are set by the hardware and cannot be changed.

**Comment by pprakash** [comment]
@SpenceKonde ... thank you very much for the clarification, Now its clear on why the pins are changing in Master Mode when compared to ISP mode. Will have my connections swapped.

**Comment by sleemanj** [comment]
On my simple pinouts I show both, "Programmer" (yellow) and "SPI" (pink) orientations for clarity - https://github.com/sleemanj/ArduinoOrientedChipPinoutCreator/blob/master/x4.png

**Comment by SpenceKonde** [comment]
Isn't that the same thing I do?

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: ***@***.***

**Comment by sleemanj** [comment]
[Your pinout image](https://raw.githubusercontent.com/SpenceKonde/ATTinyCore/master/avr/extras/ATtiny_x4.png) has master mode SPI pins denoted as DI and DO, only the programming (ISP) are shown as MOSI and MISO.

Certainly if I was looking at your diagram for a quick "now which pins are the ones to use for SPI" I would see MOSI and MISO and say "oh it's those pins are the ones to use for SPI" :-)

**Comment by sleemanj** [comment]
I'd do something like this

![Untitled2](https://user-images.githubusercontent.com/207209/149596323-62be2f5a-5d9f-42d3-92b9-c659ceafd043.jpg)

or like this

![Untitled](https://user-images.githubusercontent.com/207209/149596134-45bbbdc8-832f-4eec-bdcb-20bc9b85cb5b.jpg)

(actually instead of just "SPI" as a label, I'd use "SPI Master" perhaps)
