### ISSUE TITLE
2 serial ports on Attiny841

### ISSUE THREAD

**Issue by storfusker** [SpenceKonde/ATTinyCore#686]
Latest update

Case solved, and I can confirm that 2 serial ports on a AtTiny841 are working perfectly :-)

Br
Steen

**Comment by SpenceKonde** [comment]
I'm confused, you say nothing is coming out on serial1, then one sentence later you theorize that its' failing to handle Serial0 because it's sending data on Serial1. How could it be sending data if you're getting nothing out? o_o 

Serial0 and Serial1 are both hardware serial. Especially at such a low baud rate, sending on one should not produce any sort of conflict with the other, since all it has to to send a byte on one port is to is toss another byte from the tail of the TX buffer into the hardware serial transmit register, then the interrupt will return, at which point it will notice that there's data ready to read from receive buffer of the other port, fire that ISR and read in the data, tossing it at the head of the receiving port's RX buffer. It's not like a software serial implementation (which is blocking); both the RXC and DRE interrupts should be running fast compared to the time it takes for serial to send a byte, especially at such a low speed.  Printing an excessive volume of data becomes blocking once the TX buffer is full, but even in that case, it doesn't turn interrupts off while it waits for data to be sent so that it can fit everything into the buffer. 

Do note that the ATtiny841's internal oscillator runs significantly fast at 5V, such that it has trouble with serial communication if you don't choose the option that nudges the oscillator calibration downwards; could this be part of your issue? 

This is on the latest released version, right, not 2.0.0-dev?

If you were reporting this against 2.0.0-dev, I'd be thinking "Oh dear, maybe something is wrong with all those changes I made to reduce flash waste on the 841" but the 1.5.2 code couldn't have plausibly had a bug as severe as what you describe in such a key feature without someone having noticed and reported it - The 841 is one of the most popular ATTinyCore parts, and the dual serial ports are one of the main reasons people use it.
