### ISSUE TITLE
An error in the http://drazzy.com/package_drazzy.com_index.json file.

### ISSUE THREAD

**Issue by yendoric** [SpenceKonde/ATTinyCore#723]
extra comma at end of line 3243
causes:
"SyntaxError: JSON.parse: unexpected character at line 3242 column 11 of the JSON data"

**Comment by kelogs** [comment]
Could this be why Arduino IDE won't show up the ATTiny boards anymore ? tried to manually (re)install it without success either

**Comment by ecrzgz** [comment]
We can´t see ATTiny boards in the arduino ide, anybody know how do we resolve it?

**Comment by theosteini** [comment]
@kelogs @ecrzgz 
Yes because of this you can't see the ATTINY boards. 
To solve this go to Documents/ArduinoData. Open the .json file: package_drazzy.com_index.json 
Go to line 3241 and remove the comma and save the file. After that everything should work again. Maybe you have to open the library manager in the tools section of your Arduino IDE so that the librarys update.  
![Unbenannt](https://user-images.githubusercontent.com/91256514/189674403-0a9587c1-6e39-4d8a-8168-983cf211c05b.PNG)

**Comment by kelogs** [comment]
@theosteini yes, the libraries do update, causing a fresh copy of the .json to be downloaded. Any way around it ?

Eventually, after moving boards.txt to the variants subfolder, Arduino IDE started showing the ATtiny boards but would not compile anything:

`loading hardware from /home/kellogs/Sensory/hardware: loading package avr: invalid version dir /home/kellogs/Sensory/hardware/avr/extras/development: no major version found`

**Comment by ecrzgz** [comment]
@theosteini, Thank you very much. I think so everythink wprk properly now

**Comment by yendoric** [comment]
Do as theostini suggests, but he has line number wrong.
Save file and then make read-only.
Then try to remember to delete it when the file is eventually fixed.

**Comment by SpenceKonde** [comment]
issue with the was quiickly fixed
