### ISSUE TITLE
Recurring issues like in #753

### ISSUE THREAD

**Issue by ilisk97** [SpenceKonde/ATTinyCore#754]
Hello, it's me again from issue #753 

I just tried to compile my program on an ATtiny85 (I am using 09e0cfb) and I got a new error messages which I was able to correct:

1. avr/variants/tinyx5/pins_arduino_.h was renamed to pins_arduino.h
2. Replaced if{} with if/endif on line 129 of the same pins_arduino.h file.

I am now getting the same "error: endif without if" message that I have no idea how to fix. It's on lines 274:2 and 275:2 of pins_arduino.h for the tinyx5 series. Hope this helps!

-Ian

**Comment by SpenceKonde** [comment]
https://github.com/SpenceKonde/ATTinyCore/actions/runs/4511658635/

See the Compile Examples jobs.....

**Comment by ilisk97** [comment]
I don't follow, is the solution to the issue there? I'm still rather new to github beyond just downloading libraries, not sure what I'm looking at.

**Comment by SpenceKonde** [comment]
More recent run now that I've fixed the issue that prevented the name of the part from being shown on the left. Parts with a red X have one or more automated compile tests failing currently. 

https://github.com/SpenceKonde/ATTinyCore/actions/runs/4515681343

If you click one and all see a a whole slew of failures, then that part is busted in latest github version. 

I'm trying to get the current (very limited) set of test sketches to compile on all parts. Not there yet. But until we got CI working last week, I believed that all parts worked. That's why CI testing is 100% essential. 

There are a few parts that are failing only a couple of the tests (for example, universal wire isn't recognizing the 841/441/828,but other functionality is to the best of my knowledge working (but this is just compile tests - those don't tell you whether, when used with actual hardware, they behave correctly; that can only be determined by uploading sketches to physical chips and observing the behavior).
