### ISSUE TITLE
Please provide Board Manager URL via HTTPs 

### ISSUE THREAD

**Issue by tinxx** [SpenceKonde/ATTinyCore#767]
Hello @SpenceKonde and thanks for your excellent work!

Would you please provide the board manager URL via HTTPs, e.g., by applying [Let's Encrypt](https://letsencrypt.org/getting-started/)?

Thanks so much!
Tinx

**Comment by SpenceKonde** [comment]
Yes this is planned,  but drazzy.com is old. Both Drazzy.com and Azduino.com need to be rebuilt with latest versions and all the scripts transferred, and then lets encrypt run. Note also that Let's encrypt keeps me on such a short leash that on Azduino.com which does have it? They expire without renewal twice a year on average because the automatic renewal scripts don't work. 
If you were in my position which would take priority?
work on the core that is over a year behind the last planned update which it desperately needs. 80-90% of issue reports there are fixed issues, but the core has a bunch of bugs still in the new version and the CI is insufficient (that would be this core - I'm under pressure from all quarters to devote more time to DxCore and to a lesser extent megaTinyCore, including from my guy on the inside at Microchip.  
mTC which has a them has a critical bug and several lesser bugs that need to be fixed
DxC needs the EA-series of parts added.
Method of programming the EA-series needs to be developed. I belive significant changes are needed to SerialUPDI, and we can't pull in upstream changes because in persuit of performance (we, mostly me, increased upload speed for around 600 bytes per second to 16-24kb/s depending on the chip) 
A personal project needs the keypad read method fixed so that I can turn the lights on in my bedroom. 
Another personal project (which I have been tryingto get time to do since the first year of the pandemic is still 1 hardware rev and most of the software away from completion, plus the software for the splitters needs to be expanded to detect string length by using a resistor on the end of the "splittable" strings (splittable strings are those that use SK6805's in fairy light configurations, because they can't be daisychained, and come in multiple lengths, and COB strip, which in practical terms is maybe daisy chainable to 2 strings (I think I'm going to use 2 conductor copper tape to supply the power injection point, with white tape on top of that, and then the COB strip light if I deploy a longer string but this means tha I need to get about half a dozen E48 resistor values in stock and then and then test the detection under realistic circumstances
I have most of the hardware for an office control system done but no software
I have..... 10 designs coming back from the board house next week, every one of them needs testing, at least 1 was totally bunged, there was at least a board 11 that I forgot, someone just bought me out of yet a third board. Sooo  
I have something like 20 product descriptions to write or expand. 
I need to start patreon + github sponsors because I like eating food and living in a home instead of eating rats and living in a cardboard box. 
Oh, and I need to rebuild all my servers in AWS because they are deployed on old instance types that cost more and are strictly worse than current ones; it's a waste of time putting putting time and effort into the server that is going to be REPLACED soon right? And then to get stupid HTTPS set up something that needs to be manually poked monthly on both systems or nobody can access my cores because you can't bloody update them automatically because let's encrypt apparently doesn't trust it's users to keep control of their servers fora month at a time or something.

This means the whole configurations that I have there now ALSO need to come over - this includes the updating scripts and the stuff that support them. And there are a few places where the the apache configurations on the systems are not default either, because I have some content I need to be able to serve via http not https because I needto be able to access them with low compute power devices. 
Every day multiple issues come in. PR's? Well those come in rarely more than once a month. 
Oh and Azduino.com and my ProductInfo pages need mondo content.
Oh and there's a hyperupdi standalone programmer I'd like to get out - I have most of the hardware in stock already, but again, it's lacking the software. 
I have a lot on my plate is what I'm saying. This is on the list of things to do, but it is not the in the top 5 priorities. 

Which of those would you give priority to?

**Comment by SpenceKonde** [comment]
Oh, and I need to create pinout diagrams for 3 new tinyAVRs 4 new AVR Dx parts and 3 new AVR Ex parts. But I never generated those diagrams, I had to rely on others to create them. That's not counting I think... 3 new pin mappings that need to be added to this board and that all the new micronucleus boards need to tested and I need to adopt URBoot because as I 've said before, this core's optiboot bricks the chip by a low chance every time is reset under certain conditions because it handles erase wrong and urboot is smaller

But I need to get a build environment for urboot set up. 

And a build environment for AVRDude 7.1 set up. 

And update the versions of those that we use, and apparently it's not a dropin change, but theres no migration guide. Actually that reminds me to go complain aboutthe lack of an avrdude migration guide of any sort for core owners.
