### ISSUE TITLE
SSL for site drazzy.com is expired

### ISSUE THREAD

**Issue by spellbinder103** [SpenceKonde/ATTinyCore#847]
has troublesome when Arduino IDE download package_drazzy.com_index.json from site drazzy.com, is prompt site certificate expired.

**Comment by AIMSTEC24** [comment]
Error downloading http://drazzy.com/package_drazzy.com_index.json
SAME PROBLEM, any one here ??

**Comment by hmeijdam** [comment]
Please check this https://github.com/SpenceKonde/megaTinyCore/issues/1059#issuecomment-1950286469

**Comment by per1234** [comment]
This was resolved at one point, as was indicated by the closure of https://github.com/SpenceKonde/megaTinyCore/issues/1059 on 2024-03-29.

Unfortunately the renewed certificate expired once again yesterday, so we are back to the same problem as originally prompted the opening of this issue. Since this issue was never closed, I guess it will be best to reuse it for the new incarnation of the problem rather than opening a new issue for it.

**Comment by viniciussilverio** [comment]
Hi all, for the ones who need a workaround, you can use a proxy to bypass the certificate.

I used this one: https://us10.proxysite.com/process.php?d=fKDkvVZ0eVvjm7pEdH2n6CvjweZNeQoK8NhAdsRuzbYnTjEKE19bqBa12yY%3D&b=1

You dont need to relly on the link I shared, you can use any proxy, this is just an example, but it also works

Hope it helps

**Comment by SpenceKonde** [comment]
Corrected sometime ago.
